const {
  VITE_BACKEND_API,
  VITE_GOOGLE_CLIENT_ID,
  VITE_GITHUB_CLIENT_ID,
  VITE_RAZORPAY_KEY_ID,
  VITE_SOCKET_BACKEND_URL,
  VITE_DEVICE_METADATA_ENDPOINT,
  VITE_TEST_USER_EMAIL,
  VITE_TEST_USER_PASSWORD,
} = import.meta.env;

export const CONFIG = {
  BACKEND_API_URL: VITE_BACKEND_API,
  GOOGLE_CLIENT_ID: VITE_GOOGLE_CLIENT_ID,
  GITHUB_CLIENT_ID: VITE_GITHUB_CLIENT_ID,
  RAZORPAY_KEY_ID: VITE_RAZORPAY_KEY_ID,
  SOCKET_BACKEND_URL: VITE_SOCKET_BACKEND_URL,
  USER_METADATA_URL: VITE_DEVICE_METADATA_ENDPOINT,
  TEST_USER_EMAIL: VITE_TEST_USER_EMAIL,
  TEST_USER_PASSWORD: VITE_TEST_USER_PASSWORD,
};
